### ISSUE TITLE
Trying to train the network on different seq length instead of 30

### ISSUE THREAD

**Issue by sgalita** [PIC4SeR/AcT#3]
Hi,

I am trying to run the code using Frames : 18 instead of 30 and train the model.
I saw that it is also reading the config file under mpose/config.yaml and i changed there as well T: 18 , but still in mpose.py line 122 in function load_data i still get  that the x_train and test are (12562, **30**, 17, 3). how can i change it to be 18?

**Comment by simoneangarano** [comment]
Hi @sgalita!
You are right, the api does not allow to change sequence length at the moment. What is the behavior you would expect? 
a) return the first T frames of the sequences
b) return the last T frames of the sequences
c) return a subsampling of the sequence (interpolating frames when 30 % T != 0)
Let me know so that I can add it!
