### ISSUE TITLE
About pretrained weights

### ISSUE THREAD

**Issue by DiaQusNet** [PIC4SeR/AcT#9]
Hi, I want to know where should I put those pretrained weights files, since I have not found the information in the config file.

**Comment by simoneangarano** [comment]
I added a new test-only mode for you to test custom weights. Just put the weight file's path in config['WEIGHTS'] and run python main.py -t.
I hope this solves your problem!

**Comment by DiaQusNet** [comment]
> I added a new test-only mode for you to test custom weights. Just put the weight file's path in config['WEIGHTS'] and run python main.py -t. I hope this solves your problem!

Thanks,that will help.

**Comment by lulu110997** [comment]
Hi @simoneangarano, when loading the AcT_micro_1_0.h5 weights, I am getting this error
`ValueError: Cannot assign to variable dense_24/kernel:0 due to variable shape (52, 64) and value shape (39, 64) are incompatible`
If I used the weights in the __MACOSX dir I get 
`OSError: Unable to open file (file signature not found)`
It seems like the input to the dense_24 layer is different for the pretrained weights. Are you able to share the pretrained weights that was used in the paper please? Thank you

**Comment by simoneangarano** [comment]
Hi @lulu110997,
This is probably due to an incompatible input shape. Could you post the config.yaml file you're using?

**Comment by lulu110997** [comment]
Thanks for looking into this @simoneangarano

I am using the same config yaml from the repository. The only change I made was specifying the path to the pretrained weight. Here is the output of using git diff

```
diff --git a/utils/config.yaml b/utils/config.yaml
index 21461a2..c6f982f 100644
--- a/utils/config.yaml
+++ b/utils/config.yaml
@@ -90,4 +90,4 @@ LR_MULT: 1
 N_TRIALS: 5

 #---- TEST SETTINGS
-WEIGHTS: 'bin/AcT_micro_1_0.h5'
\ No newline at end of file
+WEIGHTS: '/home/lulu/Data/AcT_pretrained_weights/AcT_micro_1_0.h5'
\ No newline at end of file
```

I also checked the output of model summary and the shape of the dense_24 kernel. See output below

```
Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
input_1 (InputLayer)         [(None, 30, 52)]          0         
_________________________________________________________________
dense_24 (Dense)             (None, 30, 64)            3392      
_________________________________________________________________
patch_class_embedding (Patch (None, 31, 64)            2048      
_________________________________________________________________
transformer_encoder (Transfo (None, 31, 64)            199936    
_________________________________________________________________
lambda (Lambda)              (None, 64)                0         
_________________________________________________________________
dense_25 (Dense)             (None, 256)               16640     
_________________________________________________________________
dense_26 (Dense)             (None, 20)                5140      
=================================================================
Total params: 227,156
Trainable params: 227,156
Non-trainable params: 0
_________________________________________________________________
None
layer name: dense_24, weight shape: (52, 64)

```
Since I'm using the micro version, d_model=64 and since I'm using PoseNet dataset, number of keypoints=4*13=52.
If I'm not mistaken, dense_24 layer is the layer which projects the input to a higher dimension. This means that the weight of this layer should have the shape of (52, 64) (It takes as an input a matrix of shape (30, 52) and outputs a matrix of (30,64)). It seems like the [pretrained weights here](https://drive.google.com/file/d/1NRMg3BWEDHC7aqCLp1mIUxYjuqPsQ8Ty/view?usp=sharing) are for a different network which projects the input to (T, 39)

**Comment by simoneangarano** [comment]
You're right, those weights were from a previous code version. I'm retraining the models and uploading the new weights at the same link as soon as possible.

**Comment by simoneangarano** [comment]
Done, let me know if everything works now!

**Comment by lulu110997** [comment]
It works now with those weights

Do you know from which split/fold these weights are from? Also could you also provide the weights for AcT_small?

Thanks for the help!

**Comment by simoneangarano** [comment]
These weights are all from split 1 and fold 1. Download the MPOSE dataset and run the code described in the readme to obtain all the other weights; it should take a little time.
